services:
  redis:
    image: redis
    container_name: redis

  server:
    build:
      context: ./server
    image: vishal811/probov2-server
    container_name: servercontainer
    depends_on:
      - redis
    ports:
      - "3000:3000"

  engine:
    build:
      context: ./engine
    image: vishal811/probov2-engine
    container_name: engineContainer
    depends_on:
      - redis

  websocket:
    build:
      context: ./websocket
    image: vishal811/probov2-websocket
    container_name: websocketContainer
    depends_on:
      - redis
    ports:
      - "8080:8080"
